export const SystemFunctions = Object.freeze({
  Println: 'println',
  Len: 'len',
  Min: 'min',
  Max: 'max',
  Filter: 'filter',
  Includes: 'includes',
  Uuid: 'uuid',
  Date: 'date',
  Env: 'env',
  Encrypt: 'encrypt',
  Decrypt: 'decrypt',
  Arg: 'arg',
  ArgCount: 'argCount',
  Map: 'map',
  MapGet: 'mapGet',
  MapHas: 'mapHas',
  Ok: 'ok',
  Err: 'err',
  IsOk: 'isOk',
  ErrorMessage: 'errorMessage',
  Some: 'some',
  None: 'none',
  HasValue: 'hasValue',
  ValueOr: 'valueOr',
  Assert: 'assert',
  Channel: 'channel',
  Send: 'send',
  Receive: 'receive',
  Json: 'json',
  JsonGet: 'jsonGet',
  JsonGetRaw: 'jsonGetRaw',
  JsonSet: 'jsonSet',
  JsonSetPath: 'jsonSetPath',
  JsonQuote: 'jsonQuote',
  JsonStringify: 'jsonStringify',
  JsonValid: 'jsonValid',
  NewError: 'newError',
  ErrorCode: 'errorCode',
  ErrorText: 'errorText',
  ArraySum: 'arraySum',
  ArrayFirst: 'arrayFirst',
  ArrayLast: 'arrayLast',
  ArrayJoin: 'arrayJoin',
  Exec: 'exec',
  SourceSnippet: 'sourceSnippet',
  StringBuilder: 'stringBuilder',
  StringBuilderAppend: 'stringBuilderAppend',
  StringLen: 'stringLen',
  StringEquals: 'stringEquals',
  Trim: 'trim',
  Lower: 'lower',
  Upper: 'upper',
  StartsWith: 'startsWith',
  EndsWith: 'endsWith',
  Replace: 'replace',
  Split: 'split',
  IndexOf: 'indexOf',
  LastIndexOf: 'lastIndexOf',
  Contains: 'contains',
  Repeat: 'repeat',
  PadStart: 'padStart',
  PadEnd: 'padEnd',
  IntToString: 'intToString',
  StringToInt: 'stringToInt',
  ParseI32: 'parseI32',
  ParseF32: 'parseF32',
  List: 'list',
  ListPush: 'listPush',
  ListGet: 'listGet',
  ListLen: 'listLen',
  MapSet: 'mapSet',
  MapDelete: 'mapDelete',
  MapKeys: 'mapKeys',
  TokenizeSource: 'tokenizeSource',
  ParseSummary: 'parseSummary'
})

export class SystemLibrary {
  constructor() {
    this.functions = new Set(Object.values(SystemFunctions))
  }

  has(name) {
    return this.functions.has(name)
  }
}
