export const compileOnlyExamples = new Set([
  'http-api',
  'http-files',
  'http-server',
  'socket-chat'
])

export function exampleExpectations(dataText) {
  return new Map([
    ['advanced-foundation', ['12\nhello lumen\nhi compiler\n1\n', 12]],
    ['array', ['16\n', 16]],
    ['array-helpers', ['12\n3\n5\nlumen,native,chat\n', 12]],
    ['async-foundation', ['4\n', 4]],
    ['async-cancellation', ['task cancelled\n', 0]],
    ['async-error', ['boom\n', 0]],
    ['basic', ['hello\n3\n', 3]],
    ['bootstrap-compiler', ['14\nfunction\nfunctions=1 lets=1\n  let value = 1\n      ^\n', 0]],
    ['bootstrap-containers', ['hello compiler\n2\nparser\ni32\n1\n', 2]],
    ['bootstrap-exec', ['0\n', 0]],
    ['bootstrap-io', ['0\nlumen can write files\n', 0]],
    ['for-loop', ['10\n', 10]],
    ['crypto', ['1\nhello lumen\nhello lumen\n', 0]],
    ['cli-args', ['1\n3\n', 0]],
    ['control-flow', ['sum 23\n', 23]],
    ['do-until', ['10\n', 10]],
    ['env', ['from-env\nfrom-dotenv\nvariable not found\n1\n1\n', 0]],
    ['empty-array', ['0\n0\n', 0]],
    ['extern', ['hello extern\n', 0]],
    ['error-type', ['7\ndisk locked\ndisk locked\n', 7]],
    ['for-of', ['26\n', 26]],
    ['library-features', ['lumen\n1\n1\nbroken\n1\npresent\n0\nfallback\n', 0]],
    ['fs', [`${dataText}\n1\n`, 0]],
    ['http-helpers', ['1\n1\n', 0]],
    ['json', ['lumen\n3\ntrue\n', 0]],
    ['json-tools', ['lumen\n{"name":"lumen"}\ntwo\n3\n"hello \\"lumen\\""\n"hi"\n1\n0\nmicky\n', 0]],
    ['native-main', ['10\n', 10]],
    ['module-app', ['12\n', 12]],
    ['newline-continuation', ['6\n', 6]],
    ['numbers', ['10000000032\n3.750000\n1\n', 0]],
    ['patterns', ['missing\nume\n6\ncleanup\n', 6]],
    ['photon-auth', ['missing GOOGLE_CLIENT_ID\n', 0]],
    ['photon-packages', ['fallback\nvariable not found\n1\nurl package does not encode yet\n1\nemail must look like email\nlocal\nGET /health\n1\n1\n1\n1\njwt-lite does not verify signatures yet\nok string\nok number\n', 0]],
    ['photon-more-packages', ['bad empty\nvalue\n0\n1\n1\n1\nhi lumen\nfallback-arg\n0\n1\n1\n1\n{"ok":true}\n1\nfallback-map\nfirst\n1\n1\n', 0]],
    ['photon-new-packages', ['10\n1\nlumen\n1\n{"method":"GET","path":"/health","body":}\n{"method":"POST","path":"/items","body":{"name":"lumen"}}\nfallback\n1\nbuild/report.txt\narg-fallback\n0\n1\n1\n1\n1\nname: lumen\na,b,c\nlumen\n1\nGET /health\n1\n<strong>lumen</strong>\n<a href="/">home</a>\nhello-lumen\n1\nok cache\nok json\nok slug\n', 0]],
    ['println', ['total\n10\n', 10]],
    ['result-option-tools', ['ok\nbroken\nfine\nfallback\nnice fine\nnext\nhi flow\nempty\n42\n10\nflow\n', 0]],
    ['self-host-parser', ['7\n3\nlet\nnumber\nprintln\nidentifier\nreturn\nidentifier\n1\nIRModule\n3\n1\n7\nlet\nnumber\nIRModule\n1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n1\n5\n1\n7\n0\ncompile error: break outside loop\n0\ncompile error: cannot assign i32 to string\n', 0]],
    ['self-host-if-binary', ['seven\n7\n', 7]],
    ['self-host-call', ['9\n', 9]],
    ['self-host-array', ['7\n', 7]],
    ['self-host-async', ['4\n', 4]],
    ['self-host-enum-match', ['missing\n', 7]],
    ['self-host-simple', ['simple\n4\ndone\n', 4]],
    ['self-host-struct-generic', ['11\n', 11]],
    ['self-host-switch', ['20\n', 20]],
    ['self-host-try-catch', ['boom\n7\n', 7]],
    ['self-host-control', ['23\nsum 23\n1\n', 0]],
    ['self-host-tokenizer', ['10\nidentifier:function\nidentifier:main\nnumber:7\n', 0]],
    ['struct', ['11\n', 11]],
    ['string-tools', ['Hello Lumen\nhello lumen\nHELLO LUMEN\n1\n1\nhello compiler\n6\n8\n1\nhahaha\n007\nx..\n3\ngreen\n7\n2.500000\n', 7]],
    ['system', ['5\n1\n0\n1\n0\n1\n1\n4\n9\n3\n4\n5\n12\n', 12]],
    ['switch', ['23\n', 23]],
    ['socket-helpers', ['1\n', 0]],
    ['thread', ['1\n1\n1\n', 0]],
    ['try-catch', ['boom\n7\n', 7]],
    ['while-do', ['6\n', 6]]
  ])
}
