const declarations = [
  ['usesPrintf', 'declare i32 @printf(ptr, ...)'],
  ['usesStrstr', 'declare ptr @strstr(ptr, ptr)'],
  ['usesStrcmp', 'declare i32 @strcmp(ptr, ptr)'],
  ['usesFileIO', 'declare ptr @fopen(ptr, ptr)'],
  ['usesFileIO', 'declare i32 @fseek(ptr, i64, i32)'],
  ['usesFileIO', 'declare i64 @ftell(ptr)'],
  ['usesFileIO', 'declare i64 @fread(ptr, i64, i64, ptr)'],
  ['usesFileIO', 'declare i64 @fwrite(ptr, i64, i64, ptr)'],
  ['usesFileIO', 'declare ptr @lumen_alloc(i64)'],
  ['usesFileIO', 'declare i32 @fclose(ptr)'],
  ['usesFileIO', 'declare i32 @lumen_write_file(ptr, ptr)'],
  ['usesAssert', 'declare void @lumen_assert(i1, ptr)'],
  ['usesSlice', 'declare ptr @lumen_string_slice(ptr, i32, i32)'],
  ['usesBounds', 'declare i32 @lumen_bounds_check(i32, i32)'],
  ['usesBounds', 'declare ptr @lumen_string_at(ptr, i32)'],
  ['usesChannel', 'declare ptr @lumen_channel()'],
  ['usesChannel', 'declare void @lumen_send(ptr, ptr)'],
  ['usesChannel', 'declare ptr @lumen_receive(ptr)'],
  ['usesUuid', 'declare ptr @lumen_uuid()'],
  ['usesDate', 'declare ptr @lumen_date()'],
  ['usesEnv', 'declare ptr @lumen_env(ptr)'],
  ['usesCrypto', 'declare ptr @lumen_encrypt(ptr, ptr, ptr)'],
  ['usesCrypto', 'declare ptr @lumen_decrypt(ptr, ptr, ptr)'],
  ['usesArgs', 'declare ptr @lumen_arg(i32)'],
  ['usesArgs', 'declare i32 @lumen_arg_count()'],
  ['usesMaps', 'declare ptr @lumen_map(i32, ...)'],
  ['usesMaps', 'declare ptr @lumen_map_get(ptr, ptr)'],
  ['usesMaps', 'declare i1 @lumen_map_has(ptr, ptr)'],
  ['usesResults', 'declare ptr @lumen_ok(ptr)'],
  ['usesResults', 'declare ptr @lumen_err(ptr)'],
  ['usesResults', 'declare i1 @lumen_is_ok(ptr)'],
  ['usesResults', 'declare ptr @lumen_result_value(ptr)'],
  ['usesResults', 'declare ptr @lumen_error_message(ptr)'],
  ['usesOptions', 'declare ptr @lumen_some(ptr)'],
  ['usesOptions', 'declare ptr @lumen_none()'],
  ['usesOptions', 'declare i1 @lumen_has_value(ptr)'],
  ['usesOptions', 'declare ptr @lumen_value_or(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_concat(ptr, ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json(ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json_get(ptr, ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json_get_raw(ptr, ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json_set(ptr, ptr, ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json_set_path(ptr, ptr, ptr)'],
  ['usesJsonRuntime', 'declare ptr @lumen_json_stringify(ptr)'],
  ['usesJsonRuntime', 'declare i1 @lumen_json_valid(ptr)'],
  ['usesErrorRuntime', 'declare ptr @lumen_error_new(i32, ptr)'],
  ['usesErrorRuntime', 'declare i32 @lumen_error_code(ptr)'],
  ['usesErrorRuntime', 'declare ptr @lumen_error_text(ptr)'],
  ['usesArrayRuntime', 'declare ptr @lumen_array_join(i32, ptr, ptr)'],
  ['usesStringRuntime', 'declare i32 @lumen_exec(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_source_snippet(ptr, i32, i32)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_builder()'],
  ['usesStringRuntime', 'declare ptr @lumen_string_builder_append(ptr, ptr)'],
  ['usesStringRuntime', 'declare i32 @lumen_string_len(ptr)'],
  ['usesStringRuntime', 'declare i1 @lumen_string_equals(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_trim(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_lower(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_upper(ptr)'],
  ['usesStringRuntime', 'declare i1 @lumen_string_starts_with(ptr, ptr)'],
  ['usesStringRuntime', 'declare i1 @lumen_string_ends_with(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_replace(ptr, ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_split(ptr, ptr)'],
  ['usesStringRuntime', 'declare i32 @lumen_string_index_of(ptr, ptr)'],
  ['usesStringRuntime', 'declare i32 @lumen_string_last_index_of(ptr, ptr)'],
  ['usesStringRuntime', 'declare i1 @lumen_string_contains(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_repeat(ptr, i32)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_pad_start(ptr, i32, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_string_pad_end(ptr, i32, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_int_to_string(i32)'],
  ['usesStringRuntime', 'declare i32 @lumen_string_to_int(ptr)'],
  ['usesStringRuntime', 'declare float @lumen_parse_f32(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_list()'],
  ['usesStringRuntime', 'declare ptr @lumen_list_push(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_list_get(ptr, i32)'],
  ['usesStringRuntime', 'declare i32 @lumen_list_len(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_map_set(ptr, ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_map_delete(ptr, ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_map_keys(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_tokenize_source(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_parse_summary(ptr)'],
  ['usesStringRuntime', 'declare ptr @lumen_compiler_image()'],
  ['usesHttp', 'declare i32 @lumen_http_serve_files(i32, ptr)'],
  ['usesHttp', 'declare i32 @lumen_http_serve_api(i32, ptr, ptr, ptr, ptr)'],
  ['usesHttp', 'declare i32 @lumen_http_serve_http(i32, ptr, ptr, ptr, ptr, ptr, i32)'],
  ['usesHttp', 'declare i32 @lumen_socketio_serve_chat(i32, ptr)'],
  ['usesHttp', 'declare ptr @lumen_socketio_event(ptr, ptr)'],
  ['usesHttp', 'declare ptr @lumen_socketio_emit(ptr, ptr, ptr)'],
  ['usesHttp', 'declare ptr @lumen_http_request(ptr, ptr, ptr)'],
  ['usesHttp', 'declare ptr @lumen_http_response(i32, ptr, ptr)'],
  ['usesThread', 'declare ptr @lumen_semaphore_create(i32)'],
  ['usesThread', 'declare void @lumen_semaphore_wait(ptr)'],
  ['usesThread', 'declare void @lumen_semaphore_signal(ptr)'],
  ['usesThread', 'declare ptr @lumen_thread_start(ptr, ptr, ptr, ptr)'],
  ['usesThread', 'declare i32 @lumen_thread_join(ptr)'],
  ['usesThread', 'declare i32 @lumen_append_file(ptr, ptr)']
]

export function emitRuntimeABI(emitter, externs) {
  return [
    ...declarations.map(([flag, declaration]) => emitter[flag] ? declaration : ''),
    ...externs,
    emitter.debug ? 'declare void @llvm.dbg.declare(metadata, metadata, metadata)' : ''
  ]
}
